version: 1.0.{build}
image: Ubuntu1804
configuration: Release
stack: jdk 11
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  Sql__TestsBrighterConnectionString: Server=localhost;Database=BrighterTests;User ID=sa;Password=Password123!;Application Name=BrighterTests
  Sql__TestsMasterConnectionString: Server=localhost;Database=master;User ID=sa;Password=Password123!;Application Name=BrighterTests
install:
- sh: >-
    sudo snap install docker

    docker-compose up -d

    java --version

    docker ps
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
before_test:
- sh: >-
    docker ps
 
    curl http://localhost:8000/shell/
test:
  categories:
    except:
    - AWS
    - RESTMS
    - Kafka