version: 9.0.{build}
image: Ubuntu1804
configuration: Release
stack: jdk 11

services: 
- docker 
install: 
- sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
- sudo chmod +x /usr/local/bin/docker-compose 
- wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb 
- sudo dpkg -i packages-microsoft-prod.deb 
- sudo apt-get install apt-transport-https 
- sudo apt-get update 

skip_commits:
  files:
    - '**/*.md'

skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '9.0.0.0'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  Sql__TestsBrighterConnectionString: Server=localhost;Database=BrighterTests;User ID=sa;Password=Password123!;Application Name=BrighterTests
  Sql__TestsMasterConnectionString: Server=localhost;Database=master;User ID=sa;Password=Password123!;Application Name=BrighterTests

before_build:
- sh: >-
    docker-compose up -d

    java --version

    docker ps
build:
  verbosity: minimal
before_test:
- sh: >-
    docker ps
 
    curl http://localhost:8000/shell/
test:
  categories:
    except:
    - AWS
    - RESTMS
    - Kafka

artifacts:
  - path: '**\*.nupkg'

