version: 8.0.{build}
image: Ubuntu1804
configuration: Release
stack: jdk 11

skip_commits:
  files:
    - '**/*.md'

skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '8.0.0.0'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  Sql__TestsBrighterConnectionString: Server=localhost;Database=BrighterTests;User ID=sa;Password=Password123!;Application Name=BrighterTests
  Sql__TestsMasterConnectionString: Server=localhost;Database=master;User ID=sa;Password=Password123!;Application Name=BrighterTests
install:
- sh: >-
    sudo snap install docker

    docker-compose up -d

    java --version

    docker ps
build:
  verbosity: minimal
before_test:
- sh: >-
    docker ps
 
    curl http://localhost:8000/shell/
test:
  categories:
    except:
    - AWS
    - RESTMS
    - Kafka

artifacts:
  - path: '**\*.nupkg'

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/c3411953145f20a31306
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
    