version: 1.0.{build}
image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: 'Directory.Build.Props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '1.0.0.0'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - cmd: dotnet build . --configuration Release

test: off

artifacts:
  - path: '**\*.nupkg'

deploy: off
